### ISSUE TITLE
Did this break today?

### ISSUE THREAD

**Issue by God-damnit-all** [jonathanTIE/googledrive-copy-downloader#1]
It was working just fine yesterday, but today no matter what drive.google.com URL I give it, it says it's a 404. Tried re-authenticating several times. It works just fine in the browser.

**Comment by jonathanTIE** [comment]
Does it have time to show the name of the file on the cmd before the 404? Is there enough space on your drive? Does the folder "temp use for script" exists? At the moment I don't have other reports about this issue.
