### ISSUE TITLE
support `ID` or `quote exceeded` links

### ISSUE THREAD

**Issue by exisz** [jonathanTIE/googledrive-copy-downloader#4]
Thanks for this project, I now know it is possible to bypass quota using developer access, great job! 

Since my use case is primarily for bypassing quotas, I find that a link cannot be recognized if it is out of quota, so I must convert that to the standard from.

Maybe consider supporting just IDs or quota exceeded links?

It looks like this

`https://drive.google.com/uc?export=download&id=11buVHe8f6B2MyrvJelVfiRlCno3JAmpX`

Also, I think it is very cool to have a distributed mini flask app like this. I learned a lot!

**Comment by jonathanTIE** [comment]
Thanks ! 
There was an issue with the regex which didn't match the '&' char, the code should works now but I will be able to update the release only on next week-end. Then about the possibility of matching IDs directly, that could be hard to separate garbage characters from actual ID and I don't see many instances where someone would just have the ID of a file.
Thanks for the feedback ;)
