### ISSUE TITLE
Crashing when pressing Enter after pasting link

### ISSUE THREAD

**Issue by jaKz9** [jonathanTIE/googledrive-copy-downloader#5]
Using latest version (1.2), as soon as I hit Enter after pasting the drive link the program crashes and nothing happens. I tried redoing the installation process but it keeps crashing. I'm running Windows 10 1909 (18363.592).

**Comment by jonathanTIE** [comment]
What is the link that you used ? 
If there is a question mark inside it, it may be the issue and if that's the case, there is another issue about that and you need at the moment to launch the python code.

**Comment by jaKz9** [comment]
It crashes with any Google Drive link I throw at it, unfortunately. They all have a question mark in them, like so: "/view?usp=sharing".

**Comment by jonathanTIE** [comment]
Problem should be solved with 1.3.
