### ISSUE TITLE
Folder download with double extension files

### ISSUE THREAD

**Issue by NazarSurm** [jonathanTIE/googledrive-copy-downloader#6]
When downloading a folder with files named something like "Filename.7z.001, Filename.7z.002, Filename.7z.003, etc." the script seems to trim off the "001, 002, 003, etc." and just saves them all with "Filename.7z" This causes it to just download and write over the same file over and over.

**Comment by jonathanTIE** [comment]
Thanks for the report ! 1.3 should solve this issue.
